### ISSUE TITLE
Events scheduled on border dates (last column) appear as full week event on the next week

### ISSUE THREAD

**Issue by TomasWard1** [Cleveroad/cr_calendar#11]
Hello. Here is the problem:
![image](https://user-images.githubusercontent.com/35110844/184346977-4a3a92b1-2f23-4213-8058-5bee57b64592.png)
This event is scheduled on the 28th of august, and I am passing the parameter begin & end as the same DateTime.

- If I change the first day of the week, and move the event date to the new border date, the same thing happens.
- If I add minutes, or event make the end date 23:59 minutes later, same behavior.
- If I make both dates UTC, same behavior.

How can I fix this? 
I want to note that I am using a repo fork (because I needed some custom fields) so maybe this was fixed already. The fork was created on July 10th 2022.

**Comment by NikitaAmelinCR** [comment]
Hi!
Sorry for such delay! We can't reproduce your issue. Try to upgrade your fork.
