### ISSUE TITLE
Resize, drag and drop feature

### ISSUE THREAD

**Issue by Eradparvar** [Cleveroad/cr_calendar#16]
Hi thank you for sharing a beautiful library.

Are there any plans to add the ability to resize, drag and drop an event to a different time like in the syncfusion_flutter_calendar.

https://pub.dev/packages/syncfusion_flutter_calendar#calendar-features

Thank you

**Comment by ivanmyzherytskyi** [comment]
Hi, thanks for feedback!

For now events resizing and drag and drop features are not planned.
