### ISSUE TITLE
support intl:0.18.0

### ISSUE THREAD

**Issue by woei66** [Cleveroad/cr_calendar#17]
intl:0.18.0 is ready for using.
could you change the ^intl:0.17.0 to ^iintl:0.18.0?
thank you.

**Comment by ivanmyzherytskyi** [comment]
Hi!

Updated in 1.1.0 https://pub.dev/packages/cr_calendar/changelog#110

**Comment by mikolaj1982** [comment]
would it be possible to upgrade to intl: ^0.19.0
