### ISSUE TITLE
Calendar event not being added on Sunday when firstDayOfWeek: WeekDay.sunday

### ISSUE THREAD

**Issue by trueinnidhi** [Cleveroad/cr_calendar#6]
When I click on the date, I see an event. But event is not being shown in the calendar view.

**Comment by trueinnidhi** [comment]
When I click on the date, I see an event. But event is not being shown in the calendar view.

**Comment by trueinnidhi** [comment]
When I click on the date, I see an event. But event is not being shown in the calendar view.

**Comment by NikitaAmelinCR** [comment]
### The event is not being shown in the calendar view.

Extra events are not shown if the number of events is greater than maxEventLines (4 by default). In this case, +N is displayed beside the day number. You can see +1 on the screenshot.

@trueinnidhi  Please show me how the calendar looks like on Sunday in your app?

<img width="399" alt="Screenshot" src="https://user-images.githubusercontent.com/83710983/148748429-830fa98c-4927-4953-8d3a-743c0566c09a.png">

**Comment by NikitaAmelinCR** [comment]
@trueinnidhi  If you still have any questions, please reopen the issue
